version: "3.4"
services:
  sudoku:
    container_name: sudoku
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html/app
    tty: true